### ISSUE TITLE
plugin not working anymore

### ISSUE THREAD

**Issue by IronCrystal** [jdavisclark/JsFormat#196]
I don't know if there's a way to see what version of the plugin I'm using, I assume the latest version, since I recently uninstalled and re-installed it due to this bug.

I cannot run the js_format command anymore, and I see this error in my console.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/andrewpeace/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/js_formatter.py", line 88, in run
  File "/Users/andrewpeace/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/andrewpeace/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/__init__.py", line 70, in beautify
  File "/Users/andrewpeace/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/javascript/beautifier.py", line 112, in __init__
zipimport.ZipImportError: bad local file header in /Users/andrewpeace/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package
```

**Comment by desbest** [comment]
It works for me.
